#!/usr/bin/env python3
# Flow-rate test: five 25x25x3mm solid squares printed one after another, each at a
# different extrusion multiplier (M221). Pick the square whose top surface is smooth
# and fully closed without ridges: gaps/grooves = too little flow, rough/raised = too much.
import math, sys

TEMP, BED, PA, RETRACT = 235, 80, 0.04, 0.6
FLOWS = [92, 96, 100, 104, 108]            # percent, left to right
SIZE, HEIGHT = 25.0, 3.0
LH, FIRST_LH, W = 0.2, 0.25, 0.45
FIL_A = math.pi * (1.75 / 2) ** 2
Y = 150.0
XS = [70.0 + i * 40.0 for i in range(len(FLOWS))]   # 70, 110, 150, 190, 230
WALL_F, INFILL_F, TOP_F, FIRST_F, TRAVEL_F = 60 * 60, 80 * 60, 50 * 60, 25 * 60, 200 * 60
OUT = sys.argv[1] if len(sys.argv) > 1 else "PETG_flow_test_235C_92-108.gcode"

out, pos = [], [0.0, 0.0]
g = out.append

def ext(x, y, h, f):
    d = math.hypot(x - pos[0], y - pos[1])
    if d > 0:
        g(f"G1 X{x:.3f} Y{y:.3f} E{d * W * h / FIL_A:.5f} F{f}")
    pos[0], pos[1] = x, y

def travel(x, y, z, hop=0.4):
    g("G10"); g(f"G1 Z{z + hop:.3f} F1200")
    g(f"G0 X{x:.3f} Y{y:.3f} F{TRAVEL_F}")
    g(f"G1 Z{z:.3f} F1200"); g("G11")
    pos[0], pos[1] = x, y

def loop(cx, cy, size, h, f):
    half = size / 2
    pts = [(cx + half, cy - half), (cx + half, cy + half), (cx - half, cy + half), (cx - half, cy - half)]
    for p in pts:
        ext(p[0], p[1], h, f)

def square_layer(cx, cy, z, h, layer, top):
    f_wall = FIRST_F if layer == 0 else WALL_F
    f_fill = FIRST_F if layer == 0 else (TOP_F if top else INFILL_F)
    inner = SIZE - 2 * W
    travel(cx - inner / 2, cy - inner / 2, z)               # inner wall first
    loop(cx, cy, inner, h, f_wall)
    g(f"G1 X{cx - SIZE / 2:.3f} Y{cy - SIZE / 2:.3f} F{TRAVEL_F}")
    pos[0], pos[1] = cx - SIZE / 2, cy - SIZE / 2
    loop(cx, cy, SIZE, h, f_wall)                            # outer wall
    # solid zig-zag infill, alternating direction each layer
    lo = -(inner / 2) + W
    hi = (inner / 2) - W
    n = int((hi - lo) / W) + 1
    start = (cx + lo, cy + lo) if layer % 2 == 0 else (cx + lo, cy + lo)
    travel(*start, z, hop=0.0)
    for i in range(n):
        o = lo + i * W
        if layer % 2 == 0:                                   # lines along X
            a, b = (cx + lo, cy + o), (cx + hi, cy + o)
        else:                                                # lines along Y
            a, b = (cx + o, cy + lo), (cx + o, cy + hi)
        if i % 2:
            a, b = b, a
        ext(a[0], a[1], h, f_fill)
        ext(b[0], b[1], h, f_fill)

g("; PETG flow test, generated by Claude")
g("; Squares left to right (X=70,110,150,190,230): flow " + ", ".join(f"{f}%" for f in FLOWS))
poly = "[[45,135],[255,135],[255,165],[45,165]]"
g(f"EXCLUDE_OBJECT_DEFINE NAME=flow_squares CENTER=150,150 POLYGON={poly}")
g(f"PRINT_START EXTRUDER={TEMP} BED={BED} FILAMENT=PETG")
g(f"SET_PRESSURE_ADVANCE ADVANCE={PA}")
g(f"SET_RETRACTION RETRACT_LENGTH={RETRACT} RETRACT_SPEED=30 UNRETRACT_SPEED=30")
g("SET_VELOCITY_LIMIT ACCEL=3000")
g("G90"); g("M83"); g("M106 S102")
g("EXCLUDE_OBJECT_START NAME=flow_squares")
top_from = HEIGHT - 5 * LH                                  # last 5 layers count as top
for cx, flow in zip(XS, FLOWS):
    g(f"; ==== square at X={cx}: flow {flow}%")
    g(f"M221 S{flow}")
    g(f"M117 Flow {flow}%")
    g(f"G0 X{cx - (SIZE - 2 * W) / 2:.3f} Y{Y - (SIZE - 2 * W) / 2:.3f} F{TRAVEL_F}")  # move over at safe Z first
    z, layer = FIRST_LH, 0
    while z <= HEIGHT + 1e-6:
        h = FIRST_LH if layer == 0 else LH
        g(f";LAYER:{layer} Z:{z:.2f}")
        square_layer(cx, Y, z, h, layer, z > top_from)
        layer += 1
        z = round(z + LH, 3)
    g("G10"); g(f"G1 Z{HEIGHT + 5:.3f} F1200")              # clear the finished square
g("M221 S100")
g("EXCLUDE_OBJECT_END NAME=flow_squares")
g("M107")
g("PRINT_END")
open(OUT, "w").write("\n".join(out) + "\n")
print("->", OUT)
