#!/usr/bin/env python3
# Max volumetric speed test: a 60x60mm single-wall square whose print speed rises with height.
# Each 2mm band is a fixed volumetric flow (mm^3/s). Where the wall starts to show gaps,
# thin/rough lines or a matte, under-extruded look, the hotend has run out of melt capacity.
# Use ~10% below the last good band as the slicer's max volumetric speed.
import math, sys

TEMP, BED, PA, FLOW_PCT = 235, 80, 0.04, 96
RETRACT, RETRACT_SPEED = 0.4, 60
FLOWS = list(range(8, 25))                 # 8 .. 24 mm^3/s, one 2mm band each
BAND_H = 2.0
LH, FIRST_LH, W = 0.2, 0.25, 0.5          # single wall 0.5mm wide
BASE_LAYERS = 3                            # slow 2-wall base for adhesion
FIL_A = math.pi * (1.75 / 2) ** 2
CX, CY, SIZE = 150.0, 150.0, 60.0
BASE_F, TRAVEL_F = 30 * 60, 200 * 60
OUT = sys.argv[1] if len(sys.argv) > 1 else "PETG_max_flow_8-24.gcode"

out, pos = [], [0.0, 0.0]
g = out.append

def ext(x, y, h, f):
    d = math.hypot(x - pos[0], y - pos[1])
    g(f"G1 X{x:.3f} Y{y:.3f} E{d * W * h / FIL_A:.5f} F{f:.0f}")
    pos[0], pos[1] = x, y

def loop(size, h, f):
    half = size / 2
    for p in [(CX + half, CY - half), (CX + half, CY + half), (CX - half, CY + half), (CX - half, CY - half)]:
        ext(p[0], p[1], h, f)

base_h = FIRST_LH + (BASE_LAYERS - 1) * LH
total = base_h + BAND_H * len(FLOWS)
g("; PETG max volumetric speed test, generated by Claude")
g(f"; {TEMP}C, flow {FLOW_PCT}%, PA {PA}, retraction {RETRACT}mm @ {RETRACT_SPEED}mm/s, layer {LH}mm, line {W}mm")
g("; Bands of 2mm above a ~0.65mm base: " + ", ".join(f"{v}mm3/s={v / (LH * W):.0f}mm/s" for v in FLOWS))
g(f"EXCLUDE_OBJECT_DEFINE NAME=max_flow CENTER={CX},{CY} POLYGON=[[118,118],[182,118],[182,182],[118,182]]")
g(f"PRINT_START EXTRUDER={TEMP} BED={BED} FILAMENT=PETG")
g(f"SET_PRESSURE_ADVANCE ADVANCE={PA}")
g(f"SET_RETRACTION RETRACT_LENGTH={RETRACT} RETRACT_SPEED={RETRACT_SPEED} UNRETRACT_SPEED=30")
g("SET_VELOCITY_LIMIT VELOCITY=300 ACCEL=3000 SQUARE_CORNER_VELOCITY=5")
g(f"M221 S{FLOW_PCT}")
g("G90"); g("M83"); g("M106 S102")
g("EXCLUDE_OBJECT_START NAME=max_flow")
half = SIZE / 2
g("G10"); g(f"G0 X{CX - half:.3f} Y{CY - half:.3f} F{TRAVEL_F}")
pos[0], pos[1] = CX - half, CY - half
g(f"G1 Z{FIRST_LH:.3f} F1200"); g("G11")

z, layer, cur = FIRST_LH, 0, None
while z <= total + 1e-6:
    h = FIRST_LH if layer == 0 else LH
    g(f";LAYER:{layer} Z:{z:.2f}")
    g(f"G1 Z{z:.3f} F1200")
    if layer < BASE_LAYERS:
        loop(SIZE, h, BASE_F)                                  # outer
        g(f"G1 X{CX - half + W:.3f} Y{CY - half + W:.3f} F{TRAVEL_F}")
        pos[0], pos[1] = CX - half + W, CY - half + W
        loop(SIZE - 2 * W, h, BASE_F)                          # inner
        g(f"G1 X{CX - half:.3f} Y{CY - half:.3f} F{TRAVEL_F}")
        pos[0], pos[1] = CX - half, CY - half
    else:
        band = min(int((z - base_h - 1e-6) // BAND_H), len(FLOWS) - 1)
        vol = FLOWS[band]
        if vol != cur:
            g(f"; ---- band {band + 1}: {vol} mm3/s from Z={z:.2f}")
            g(f"M117 Flow {vol}mm3/s")
            cur = vol
        loop(SIZE, h, vol / (h * W) * 60)
    layer += 1
    z = round(z + LH, 3)

g("EXCLUDE_OBJECT_END NAME=max_flow")
g("G10"); g("M221 S100"); g("M107")
g("SET_VELOCITY_LIMIT VELOCITY=300 ACCEL=3000 SQUARE_CORNER_VELOCITY=5")
g("PRINT_END")
open(OUT, "w").write("\n".join(out) + "\n")
print("layers", layer, "height", round(total, 2), "->", OUT)
