#!/usr/bin/env python3
# Pressure advance tower (Klipper method): a 40x40mm two-wall square printed fast
# (100 mm/s) at low accel (500) and square_corner_velocity 1, so corner bulges are
# easy to see. Pressure advance steps up every 4mm; pick the band with the sharpest corners.
import math, sys

TEMP = 235
BED = 80
PA_VALUES = [round(0.01 * i, 2) for i in range(11)]   # 0.00 .. 0.10
SEG_H = 4.0
LH, FIRST_LH, W = 0.2, 0.25, 0.45
FIL_A = math.pi * (1.75 / 2) ** 2
CX, CY, SIZE = 150.0, 150.0, 40.0
WALL_F, FIRST_F, TRAVEL_F = 100 * 60, 25 * 60, 200 * 60
OUT = sys.argv[1] if len(sys.argv) > 1 else "PETG_PA_tower_235C_0-0.10.gcode"

out, pos = [], [0.0, 0.0]
g = out.append

def ext(x, y, h, f):
    d = math.hypot(x - pos[0], y - pos[1])
    g(f"G1 X{x:.3f} Y{y:.3f} E{d * W * h / FIL_A:.5f} F{f}")
    pos[0], pos[1] = x, y

def square(size, z, h, f, start_travel):
    half = size / 2
    pts = [(CX - half, CY - half), (CX + half, CY - half), (CX + half, CY + half),
           (CX - half, CY + half), (CX - half, CY - half)]
    if start_travel:
        g("G10"); g(f"G1 Z{z + 0.4:.3f} F1200")
        g(f"G0 X{pts[0][0]:.3f} Y{pts[0][1]:.3f} F{TRAVEL_F}")
        g(f"G1 Z{z:.3f} F1200"); g("G11")
    else:
        g(f"G1 X{pts[0][0]:.3f} Y{pts[0][1]:.3f} F{TRAVEL_F}")
    pos[0], pos[1] = pts[0]
    for p in pts[1:]:
        ext(p[0], p[1], h, f)

total_h = SEG_H * len(PA_VALUES)
g("; PETG pressure advance tower, generated by Claude")
g("; PA per 4mm band, bottom to top: " + ", ".join(str(v) for v in PA_VALUES))
g("EXCLUDE_OBJECT_DEFINE NAME=pa_tower CENTER=150,150 POLYGON=[[128,128],[172,128],[172,172],[128,172]]")
g(f"PRINT_START EXTRUDER={TEMP} BED={BED} FILAMENT=PETG")
g("SET_RETRACTION RETRACT_LENGTH=0.6 RETRACT_SPEED=30 UNRETRACT_SPEED=30")
g("SET_VELOCITY_LIMIT ACCEL=500 SQUARE_CORNER_VELOCITY=1")
g("G90"); g("M83"); g("M106 S102")
g("EXCLUDE_OBJECT_START NAME=pa_tower")

z, layer, cur = FIRST_LH, 0, None
while z <= total_h + 1e-6:
    seg = min(int((z - 1e-6) // SEG_H), len(PA_VALUES) - 1)
    pa = PA_VALUES[seg]
    if pa != cur:
        g(f"; ---- band {seg + 1}: PA {pa} from Z={z:.2f}")
        g(f"SET_PRESSURE_ADVANCE ADVANCE={pa}")
        g(f"M117 PA {pa}")
        cur = pa
    h = FIRST_LH if layer == 0 else LH
    f = FIRST_F if layer == 0 else WALL_F
    g(f";LAYER:{layer} Z:{z:.2f}")
    g(f"G1 Z{z:.3f} F1200")
    square(SIZE - 2 * W, z, h, f, start_travel=True)   # inner wall first
    square(SIZE, z, h, f, start_travel=False)          # outer wall, short move out
    layer += 1
    z = round(z + LH, 3)

g("EXCLUDE_OBJECT_END NAME=pa_tower")
g("G10"); g("M107")
g("SET_PRESSURE_ADVANCE ADVANCE=0")
g("SET_VELOCITY_LIMIT SQUARE_CORNER_VELOCITY=5")
g("PRINT_END")
open(OUT, "w").write("\n".join(out) + "\n")
print("layers", layer, "->", OUT)
