#!/usr/bin/env python3
# PETG temperature tower: two 10x10mm hollow pillars 30mm apart (stringing gap),
# 2 perimeters each, 5mm per temperature segment, hottest at the bottom.
import math

TEMPS = [35, 40, 45, 50, 55, 60]   # retraction speeds mm/s, bottom to top (length fixed at 0.4mm)
TEMP = 235
SEG_H = 5.0
LH = 0.2
FIRST_LH = 0.25
W = 0.45                                   # line width
FIL_A = math.pi * (1.75 / 2) ** 2
BED = 80
CX, CY = 150.0, 150.0
PILLAR = 10.0
GAP = 30.0                                 # centre-to-centre distance
WALL_F = 60 * 60                           # 60 mm/s
FIRST_F = 25 * 60
TRAVEL_F = 200 * 60

out = []
e_total = 0.0
pos = [0.0, 0.0]

def g(s):
    out.append(s)

def ext(x, y, h, f):
    global e_total
    d = math.hypot(x - pos[0], y - pos[1])
    e = d * W * h / FIL_A
    g(f"G1 X{x:.3f} Y{y:.3f} E{e:.5f} F{f}")
    pos[0], pos[1] = x, y

def travel(x, y, z, hop=True):
    if hop:
        g("G10")
        g(f"G1 Z{z + 0.4:.3f} F1200")
    g(f"G0 X{x:.3f} Y{y:.3f} F{TRAVEL_F}")
    if hop:
        g(f"G1 Z{z:.3f} F1200")
        g("G11")
    pos[0], pos[1] = x, y

def square(cx, cy, size, z, h, f):
    half = size / 2
    pts = [(cx - half, cy - half), (cx + half, cy - half),
           (cx + half, cy + half), (cx - half, cy + half), (cx - half, cy - half)]
    travel(*pts[0], z)
    for p in pts[1:]:
        ext(p[0], p[1], h, f)

pillars = [(CX - GAP / 2, CY), (CX + GAP / 2, CY)]
total_h = SEG_H * len(TEMPS)

g("; PETG retraction SPEED tower: 0.4mm at 35-60mm/s, 235C, PA 0.04, generated by Claude")
g("; Segments (bottom to top), each 5mm: " + ", ".join(f"{t}mm/s" for t in TEMPS))
g("EXCLUDE_OBJECT_DEFINE NAME=tower CENTER=150,150 POLYGON=[[130,140],[170,140],[170,160],[130,160]]")
g(f"PRINT_START EXTRUDER={TEMP} BED={BED} FILAMENT=PETG")
g("SET_RETRACTION RETRACT_LENGTH=0.4 UNRETRACT_SPEED=30")
g("SET_PRESSURE_ADVANCE ADVANCE=0.04")
g("SET_VELOCITY_LIMIT ACCEL=3000")
g("G90")
g("M83")
g("M106 S102")                              # ~40% part fan for PETG
g("EXCLUDE_OBJECT_START NAME=tower")

z = FIRST_LH
layer = 0
cur_temp = None
while z <= total_h + 1e-6:
    seg = min(int((z - 1e-6) // SEG_H), len(TEMPS) - 1)
    t = TEMPS[seg]
    if t != cur_temp:
        g(f"; ---- segment {seg + 1}: retract speed {t}mm/s from Z={z:.2f}")
        g(f"SET_RETRACTION RETRACT_SPEED={t}")
        g(f"M117 Retract {t}mm/s")
        cur_temp = t
    h = FIRST_LH if layer == 0 else LH
    f = FIRST_F if layer == 0 else WALL_F
    g(f";LAYER:{layer} Z:{z:.2f}")
    g(f"G1 Z{z:.3f} F1200")
    for (px, py) in pillars:
        square(px, py, PILLAR, z, h, f)                 # outer perimeter
        square(px, py, PILLAR - 2 * W, z, h, f)         # inner perimeter
    layer += 1
    z = round(z + LH, 3)

g("EXCLUDE_OBJECT_END NAME=tower")
g("G10")
g("M107")
g("SET_RETRACTION RETRACT_LENGTH=0.1 RETRACT_SPEED=30")
g("PRINT_END")

open("/private/tmp/claude-501/-Users-ross-Downloads/2f76fb1e-b654-4e0e-9445-0f41c9f59888/scratchpad/PETG_retract_speed_tower_0.4mm_35-60.gcode", "w").write("\n".join(out) + "\n")
print("layers", layer, "lines", len(out))
